version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=mongodb://mongodb:27017/provisioning
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=${aws.access-key}
      - AWS_SECRET_ACCESS_KEY=${aws.secret-key}
      - AWS_SQS_QUEUE_URL=${aws.sqs.queue-url}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
